version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-orders-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - orders-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel-orders-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - orders-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: laravel-orders-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_ROOT_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - orders-network

  redis:
    image: redis:7-alpine
    container_name: laravel-orders-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - orders-network

networks:
  orders-network:
    driver: bridge

volumes:
  pgdata: 